### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by Upcycle-Electronics** [manfrotto73/Eater-6502#1]
Export your files as a PDF so others can view what you've done easier. For instance, I'm usually not on a computer when surfing the web socially. While I am on KiCAD regularly, I'm usually working on my own stuff. I can't view your files from a tablet. Also, you might mention your design specs like board size, layers, etc. I've seen a bunch of people building stuff for Ben's project, but I'm curious if anyone is actually etching boards themselves. I got around 90% done with a 6502 design for DIY etching a few weeks ago, (not uploaded). I'm not going to etch until I have a TL866 and/or have a working USB to UART interface. Anyways...good luck with it.
-Jake

**Comment by manfrotto73** [comment]
PDF files have been uploaded
